import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

import { loadProject } from "./loadProject";

import type { LoadProjectOutput } from "./types";

/**
 * Golden-master coverage for reading a **Zarr v2** archive stamped with Piximi
 * format version 2.x — i.e. exactly what the shipped 2.0.0 build saves.
 *
 * `saveProject.test.ts` writes and reads with the same code, so it cannot tell
 * whether the reader still understands an archive produced by a *previous*
 * writer. That matters the moment the on-disk Zarr format changes while the
 * Piximi format version stays 2.x: `detectVersion` routes on the app version,
 * so one reader has to serve both wire formats, and a self-round-trip suite
 * stays green while every archive in the wild breaks.
 *
 * These fixtures were captured from the zarr.js writer (see
 * `__fixtures__/README.md`) and must not be regenerated by a later writer —
 * regenerating them destroys the only coverage of the older format.
 */
const FIXTURE_DIR = "src/core/file-io/__fixtures__";

const load = async (file: string): Promise<LoadProjectOutput> => {
  const bytes = await readFile(`${FIXTURE_DIR}/${file}`);
  // `readFile` hands back a Buffer, which can be a view onto a pooled
  // allocation. Copy to a plain Uint8Array so the File holds exactly these
  // bytes — and so the type is a `BlobPart`.
  const asFile = new File([new Uint8Array(bytes)], file, {
    type: "application/zip",
  });
  return loadProject({ files: [asFile] }, { cancelled: false }, () => {});
};

describe("zarr-v2-on-disk archive at Piximi format 2.x", () => {
  it("routes through detectVersion to the v2 reader and restores the project", async () => {
    const { project } = await load("golden-v2-zarrv2.zip");
    const { data } = project;

    expect(data.images.ids).toEqual(["image-1", "image-2"]);
    expect(data.imageSeries.ids).toEqual(["series-1", "series-2"]);
    expect(data.planes.ids).toEqual(["plane-1", "plane-2", "plane-3"]);
    expect(data.channels.ids).toEqual([
      "channel-1",
      "channel-2",
      "channel-3",
      "channel-4",
    ]);
    expect(data.kinds.ids).toEqual(["Image", "cell", "nucleus"]);
    expect(data.annotations.ids).toHaveLength(3);
    expect(data.experiment.id).toBe("exp-1");
  });

  it("restores channel pixels byte-exactly at both bit depths", async () => {
    const { project } = await load("golden-v2-zarrv2.zip");
    const channels = project.data.channels;

    // 8-bit, 3x4 — and 16-bit, 2x2. The uint16 case is the one where a wrong
    // element width silently yields half an image rather than an error.
    const eightBit = channels.entities["channel-1"]!;
    expect(eightBit.bitDepth).toBe(8);
    expect(eightBit.data.byteLength).toBe(12);
    expect(Array.from(new Uint8Array(eightBit.data))).toEqual([
      49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126,
    ]);

    const sixteenBit = channels.entities["channel-3"]!;
    expect(sixteenBit.bitDepth).toBe(16);
    expect(sixteenBit.data.byteLength).toBe(8);
    expect(Array.from(new Uint16Array(sixteenBit.data))).toEqual([
      51, 58, 65, 72,
    ]);
  });

  it("restores ragged annotation masks from the concatenated dataset", async () => {
    const { project } = await load("golden-v2-zarrv2.zip");
    const annotations = project.data.annotations;

    expect(annotations.ids).toEqual([
      "annotation-1",
      "annotation-2",
      "annotation-3",
    ]);

    const masks = annotations.ids.map((id) =>
      Array.from(annotations.entities[id]!.encodedMask),
    );
    // All three RLE runs live in one concatenated dataset, sliced back apart by
    // CSR-style offsets. The runs are ragged and of differing lengths, so an
    // off-by-one in the offsets still yields three arrays — compare values, not
    // lengths.
    expect(masks).toEqual([
      [0, 2, 1, 1],
      [1, 3],
      [0, 1, 2, 1, 3],
    ]);
  });

  it("restores classifier run history and eval results", async () => {
    const { project } = await load("golden-v2-zarrv2.zip");
    const info =
      project.classifier.kindClassifiers.Image.modelInfoDict["SimpleCNN-1"];

    expect(info.valid).toBe(true);
    expect(info.runs).toHaveLength(1);

    const run = info.runs[0];
    expect(run.history).toHaveLength(2);
    // Float64 on disk specifically so training metrics survive untouched.
    expect(run.history[0].loss).toBe(0.9);
    expect(run.history[1].valAccuracy).toBe(0.75);
    expect(run.evalResults?.confusionMatrix).toEqual([
      [5, 1],
      [2, 4],
    ]);
    expect(run.evalResults?.accuracy).toBe(0.75);
    // Not 255-truncated, and not re-rounded.
    expect(run.hyperparameters.preprocess.inputShape).toEqual({
      planes: 1,
      height: 512,
      width: 300,
      channels: 2,
    });
    expect(run.hyperparameters.optimizer.learningRate).toBe(
      info.optimizerSettings.learningRate,
    );
  });

  it("recovers each model's real name from its manifest", async () => {
    const { modelFiles } = await load("golden-v2-zarrv2.zip");

    // "MobileNet.v2" is stored in the folder `models/MobileNet_v2/`; the
    // unmangled name is only recoverable from the manifest.
    expect(Object.keys(modelFiles).sort()).toEqual([
      "MobileNet.v2",
      "SimpleCNN-1",
    ]);
  });
});

describe("zarr-v2-on-disk edge cases", () => {
  /**
   * Non-finite numbers reached `.zattrs` as `null` under zarr.js, which the
   * readers' `optional()` already maps away. A writer that serializes them as
   * the *strings* `"NaN"`/`"Infinity"` instead would round-trip a string into
   * a number-typed field, silently poisoning any arithmetic downstream.
   */
  it("reads non-finite statistics back as absent, never as a string", async () => {
    const { project } = await load("golden-v2-zarrv2-edge.zip");

    const channel = project.data.channels.entities["channel-1"]!;
    for (const stat of [channel.mean, channel.std]) {
      expect(typeof stat).not.toBe("string");
      expect(stat === undefined || stat === null || Number.isNaN(stat)).toBe(
        true,
      );
    }

    const info =
      project.classifier.kindClassifiers.Image.modelInfoDict["acc 100%"];
    const evalResults = info.runs[0].evalResults!;
    for (const metric of [
      evalResults.precision,
      evalResults.recall,
      evalResults.f1Score,
    ]) {
      expect(typeof metric).not.toBe("string");
    }
    // Finite metrics in the same block must survive untouched.
    expect(evalResults.accuracy).toBe(0.75);
  });

  /**
   * Falsy scalars are stored as `0`. A `getAttr` that gates on truthiness
   * rather than key presence rejects every one of these, so a project with
   * shuffle disabled simply fails to open.
   */
  it("reads falsy scalar attributes rather than treating them as absent", async () => {
    const { project } = await load("golden-v2-zarrv2-edge.zip");

    const info =
      project.classifier.kindClassifiers.Image.modelInfoDict["acc 100%"];
    expect(info.valid).toBe(false);
    expect(info.preprocessSettings.shuffle).toBe(false);
    expect(info.preprocessSettings.normalizeOptions.normalize).toBe(false);
    expect(info.preprocessSettings.normalizeOptions.center).toBe(false);
    expect(info.preprocessSettings.cropOptions.numCrops).toBe(0);
    expect(project.data.channelMetas.entities["meta-1"]!.visible).toBe(false);
  });

  /**
   * Model names are user-typed and become zarr group names verbatim. `%` and
   * `#` are the characters a URL-based path resolver cannot carry: `%` makes
   * `decodeURIComponent` throw, and `#` truncates the path, collapsing two
   * distinct models onto one key.
   */
  it("finds model groups whose names contain URL-unsafe characters", async () => {
    const { project } = await load("golden-v2-zarrv2-edge.zip");
    const dict = project.classifier.kindClassifiers.Image.modelInfoDict;

    expect(Object.keys(dict).sort()).toEqual(["acc 100%", "run#2"]);
    // Distinct keys, not one silently overwriting the other.
    expect(dict["acc 100%"]).toBeDefined();
    expect(dict["run#2"]).toBeDefined();
    expect(project.classifier.kindClassifiers.Image.activeModel).toBe(
      "acc 100%",
    );
  });
});
