import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  container: {
    bottom: 0,
    height: "100%",
    left: 0,
    position: "fixed",
    right: 0,
    top: 0,
    width: "100%",
    zIndex: 10,
  },
  selection: {
    display: "block",
    height: "100%",
    left: 0,
    position: "absolute",
    top: 0,
    width: "100%",
    zIndex: 10,
  },
  image: {
    display: "block",
    height: "100%",
    left: 0,
    position: "absolute",
    top: 0,
    width: "100%",
    zIndex: 14,
  },
  interface: {
    display: "block",
    height: "100%",
    left: 0,
    position: "absolute",
    top: 0,
    width: "100%",
    zIndex: 15,
  },
  temporary: {
    display: "block",
    height: "100%",
    left: 0,
    position: "absolute",
    top: 0,
    width: "100%",
    zIndex: 12,
  },
}));
