#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(ts|tsx|js|jsx)$") || true

if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs ./scripts/lint.sh
fi

pnpm run no-console-logs

# enable for testing, run `HUSKY_DEBUG=true git commit -m "..."`
# exit 1