name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/setup@v1
        with:
          version: 11.2.2
          runtime: node@24
          cache: true

      - name: Install Packages
        # @tensorflow/tfjs-node canvas core-js esbuild
        run: pnpm install --dangerously-allow-all-builds

      - name: Lint code
        run: pnpm run lint

      - name: Build page
        run: pnpm build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: gh-pages
          cname: piximi.app
