name: Test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Start App Server
        run: pnpm start &
        env:
          NODE_ENV: test

      - name: Wait for Server to Start
        run: npx wait-on http://localhost:3000

      - name: Run Tests
        run: pnpm test --silent
        env:
          CI: true
